Zemedya.AspNetCoreMVC/Controllers/PanelController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Zemedya.AspNetCoreMVC.Models;
using Zemedya.Business.Abstract.UnitOfWork;
using Zemedya.Model.DTO.AyarlarDTOs;
using Zemedya.Model.DTO.BlogDTOs;
using Zemedya.Model.DTO.DuyuruDTOs;
using Zemedya.Model.DTO.EkipDTOs;
using Zemedya.Model.DTO.EtkinlikDTOs;
using Zemedya.Model.DTO.GaleriDTOs;
using Zemedya.Model.DTO.GirisDTO;
using Zemedya.Model.DTO.HaberDTOs;
using Zemedya.Model.DTO.IletisimDTOs;
using Zemedya.Model.DTO.KariyerFirsatiDTOs;
using Zemedya.Model.DTO.KurumsalDTOs;
using Zemedya.Model.DTO.PopupDTOs;
using Zemedya.Model.DTO.ReferansDTOs;
using Zemedya.Model.DTO.SliderDTOs;
using Zemedya.Model.DTO.UrunDTOs;
using Zemedya.Model.DTO.VideoDTOs;
using Zemedya.Model.DTO.YoneticiDTOs;
using Zemedya.Model.VM;
using Zemedya.Model.VM.Page;

namespace Zemedya.AspNetCoreMVC.Controllers
{
    public class PanelController : Controller
    {
        private IUnitOfWork _unitOfWork;
        public PanelController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Video()
        {
            var videolar = _unitOfWork.VideoManager.HepsiniGetir();
            var dil = _unitOfWork.MevcutDillerManager.Getir(x => x.Id == 1);
            ViewBag.en = dil.EN.ToString();
            return View(videolar);
        }

        [Authorize]
        public IActionResult KontrolPaneli()
        {
            KontrolPaneliVM kontrolPaneliVM = new KontrolPaneliVM
            {
                MevcutSayfalar = _unitOfWork.MevcutSayfalarManager.Getir(x => x.Id == 1),
                MevcutDiller = _unitOfWork.MevcutDillerManager.Getir(x => x.Id == 1)
            };
            return View(kontrolPaneliVM);
        }


        public ActionResult PasifeCevirSayfa(string Id)
        {
            var sayfa = _unitOfWork.MevcutSayfalarManager.Getir(x => x.Id == 1);
            if (Id == "1")
            {
                if (sayfa.Haberler)
                {
                    sayfa.Haberler = false;
                }
                else
                {
                    sayfa.Haberler = true;
                }
            }
            else if (Id == "2")
            {
                if (sayfa.Duyuru)
                {
                    sayfa.Duyuru = false;
                }
                else
                {
                    sayfa.Duyuru = true;
                }
            }
            else if (Id == "3")
            {
                if (sayfa.Blog)
                {
                    sayfa.Blog = false;
                }
                else
                {
                    sayfa.Blog = true;
                }
            }
            else if (Id == "31")
            {
                if (sayfa.BlogKategori)
                {
                    sayfa.BlogKategori = false;
                }
                else
                {
                    sayfa.BlogKategori = true;
                }
            }
            else if (Id == "4")
            {
                if (sayfa.Etkinlik)
                {
                    sayfa.Etkinlik = false;
                }
                else
                {
                    sayfa.Etkinlik = true;
                }
            }
            else if (Id == "5")
            {
                if (sayfa.Iletisim)
                {
                    sayfa.Iletisim = false;
                }
                else
                {
                    sayfa.Iletisim = true;
                }
            }
            else if (Id == "6")
            {
                if (sayfa.Kurumsal)
                {
                    sayfa.Kurumsal = false;
                }
                else
                {
                    sayfa.Kurumsal = true;
                }
            }
            else if (Id == "7")
            {
                if (sayfa.Referans)
                {
                    sayfa.Referans = false;
                }
                else
                {
                    sayfa.Referans = true;
                }
            }
            else if (Id == "8")
            {
                if (sayfa.Urunler)
                {
                    sayfa.Urunler = false;
                }
                else
                {
                    sayfa.Urunler = true;
                }
            }
            else if (Id == "81")
            {
                if (sayfa.UrunKategori)
                {
                    sayfa.UrunKategori = false;
                }
                else
                {
                    sayfa.UrunKategori = true;
                }
            }
            else if (Id == "9")
            {
                if (sayfa.Video)
                {
                    sayfa.Video = false;
                }
                else
                {
                    sayfa.Video = true;
                }
            }
            else if (Id == "10")
            {
                if (sayfa.Ekip)
                {
                    sayfa.Ekip = false;
                }
                else
                {
                    sayfa.Ekip = true;
                }
            }
            else if (Id == "11")
            {
                if (sayfa.Galeri)
                {
                    sayfa.Galeri = false;
                }
                else
                {
                    sayfa.Galeri = true;
                }
            }
            else if (Id == "111")
            {
                if (sayfa.GaleriKategori)
                {
                    sayfa.GaleriKategori = false;
                }
                else
                {
                    sayfa.GaleriKategori = true;
                }
            }

            _unitOfWork.MevcutSayfalarManager.Guncelle(sayfa);
            _unitOfWork.Complete();
            _unitOfWork.Dispose();

            return Json(new
            {
                success = true,
            });
        }

        [HttpPost]
        public ActionResult PasifeCevirDil(string Id)
        {
            var dil = _unitOfWork.MevcutDillerManager.Getir(x => x.Id == 1);
            if (Id == "2")
            {
                if (dil.EN)
                {
                    dil.EN = false;
                }
                else
                {
                    dil.EN = true;
                }
            }
            
            _unitOfWork.MevcutDillerManager.Guncelle(dil);
            _unitOfWork.Complete();
            _unitOfWork.Dispose();

            return Json(new
            {
                success = true,
            });
        }


        [HttpPost]
        public ActionResult VideoEkle([FromForm] VideoDTO videoDTO, IFormFile resim, IFormFile resimEN)
        {
            if (resim != null)
            {
                string uzanti = Path.GetExtension(resim.FileName);
                string resimAd = Guid.NewGuid() + uzanti;
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/" + resimAd);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    resim.CopyTo(stream);
                }
                videoDTO.Gorsel = resimAd;
            }
            else
            {
                videoDTO.Gorsel = "null.png";
            }
            if (resimEN != null)
            {
                string uzantiEN = Path.GetExtension(resimEN.FileName);
                string resimAdEN = Guid.NewGuid() + uzantiEN;
                string pathEN = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/" + resimAdEN);
                using (var streamEN = new FileStream(pathEN, FileMode.Create))
                {
                    resimEN.CopyTo(streamEN);
                }
                videoDTO.GorselEN = resimAdEN;
            }
            else
            {
                videoDTO.GorselEN = "null.png";
            }
            _unitOfWork.VideoManager.Ekle(videoDTO);
            _unitOfWork.Complete();
            _unitOfWork.Dispose();
            return Json(new
            {
                success = true,
                result = 1
            });
        }


        public ActionResult VideoGuncelle([FromForm] string Id)
        {
            var entity = _unitOfWork.VideoManager.Getir(x => x.Id == int.Parse(Id));
            return Json(new
            {
                success = true,
                ad = entity.Ad,
                adEN = entity.AdEN,
                baslik = entity.Baslik,
                baslikEN = entity.BaslikEN,
                videourl = entity.VideoUrl,
                videourlEN = entity.VideoUrlEN,
                gorsel = entity.Gorsel,
                gorselEN = entity.GorselEN,
                aktif = entity.Aktif
            });
        }

        public ActionResult VideoGuncel([FromForm] VideoDTO videoDTO, IFormFile resim, IFormFile resimEN)
        {
            var video = _unitOfWork.VideoManager.Getir(x => x.Id == videoDTO.Id);
            if (resim != null)
            {
                string uzanti = Path.GetExtension(resim.FileName);
                string resimAd = Guid.NewGuid() + uzanti;
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/" + resimAd);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    resim.CopyTo(stream);
                }
                videoDTO.Gorsel = resimAd;

Zemedya.AspNetCoreMVC/Views/Panel/HaberEkle.cshtml
@model Zemedya.Model.VM.HaberEkleVM
@{
    ViewData["Title"] = "HaberEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="card card-custom">
        <div class="card-header">
            <h3 class="card-title">
                Haber Ekle
            </h3>
            @if (ViewBag.en == "True")
            {
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item ">
                        <a class="nav-link active float-right" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">TR</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link float-right" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">EN</a>
                    </li>
                </ul>
            }

        </div>
        <p style="color:red;" class="mt-5 ml-5">@ViewData["hata"]</p>
        <form method="post" id="haberform" enctype="multipart/form-data">
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active " id="home" role="tabpanel" aria-labelledby="home-tab">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group" style="display:none;">
                                    <label asp-for="HaberDTO.HaberKategoriId">Kategori</label>
                                    <input type="text" asp-for="HaberDTO.HaberKategoriId" value="1" />
                                </div>
                                <div class="form-group">
                                    <label>Ad</label>
                                    <input maxlength="500" asp-for="HaberDTO.Isim" class="form-control" placeholder="Ad" />
                                </div>
                                <div class="form-group">
                                    <label>SEO</label>
                                    <input asp-for="HaberDTO.SEO" class="form-control" placeholder="SEO" />
                                </div>
                                <div class="form-group">
                                    <label>Tarih</label>
                                    <input asp-for="HaberDTO.Tarih" class="form-control" type="date" />
                                </div>
                                <div class="form-group mb-1">
                                    <label>Özet</label>
                                    <textarea maxlength="1000" asp-for="HaberDTO.Ozet" class="form-control"></textarea>
                                </div>

                            </div>
                            <div class="col-md-6">
                                
                                <div class="form-group mb-1">
                                    <label for="exampleTextarea">Detay</label>
                                    <textarea asp-for="HaberDTO.Detay" class="form-control" rows="3" style="height: 127px;"></textarea>
                                </div>
                                <div class="form-group float-md-left">
                                    <div class="mt-4">Görsel</div>
                                    <div class="image-input image-input-outline mt-2">
                                        <img id="Resim" height="160" width="160" src="~/img/null.png" />
                                        <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Change avatar">
                                            <i class="fa fa-pen icon-sm text-muted"></i>
                                            <input type="file" asp-for="Gorsel" accept=".png, .jpg, .jpeg" />
                                            <input type="hidden" name="profile_avatar_remove" />
                                        </label>
                                    </div>
                                    <div class="mt-0 pt-0 ml-48">
                                        <a onclick="gorselKaldır()" class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow mt-lg-0 pt-lg-0 ml-7"><i class="ki ki-bold-close icon-xs text-muted"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="tab-pane fade " id="profile" role="tabpanel" aria-labelledby="profile-tab">

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Ad(EN)</label>
                                    <input asp-for="HaberDTO.IsimEN" class="form-control" placeholder="Ad" />
                                </div>
                                <div class="form-group">
                                    <label>SEO(EN)</label>
                                    <input asp-for="HaberDTO.SEOEN" class="form-control" placeholder="SEO" />
                                </div>
                                <div class="form-group mb-1">
                                    <label>Özet(EN)</label>
                                    <textarea asp-for="HaberDTO.OzetEN" class="form-control"></textarea>
                                </div>
                            </div>
                            <div class="col-md-6">

                                <div class="form-group mb-1">
                                    <label for="exampleTextarea">Detay(EN)</label>
                                    <textarea asp-for="HaberDTO.DetayEN" class="form-control" rows="3" style="height: 127px;"></textarea>
                                </div>
                                <div class="form-group float-md-left">
                                    <div class="mt-4">Görsel(EN)</div>
                                    <div class="image-input image-input-outline mt-2">
                                        <img id="ResimEN" height="160" width="160" src="~/img/null.png" />
                                        <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Change avatar">
                                            <i class="fa fa-pen icon-sm text-muted"></i>
                                            <input type="file" asp-for="GorselEN" accept=".png, .jpg, .jpeg" />
                                            <input type="hidden" name="profile_avatar_remove" />
                                        </label>
                                    </div>
                                    <div class="mt-0 pt-0 ml-48">
                                        <a onclick="gorselKaldırEN()" class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow mt-lg-0 pt-lg-0 ml-7"><i class="ki ki-bold-close icon-xs text-muted"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="card-footer">
                    <input type="submit" value="Kaydet" onclick="return haberEkle()" class="btn btn-primary mr-2" />
                    <button asp-action="Haberler" asp-controller="Panel" class="btn btn-secondary">İptal</button>
                </div>
            </div>
        </form>
        <!--begin::Form-->
        <!--end::Form-->
    </div>
</div>
@section Javascript{

    <script type="text/javascript">
            
        

        $("#HaberDTO_SEO").on('keyup change', function () {
            validateSEOInput('HaberDTO_SEO');
        });

        $('#HaberDTO_SEO').bind("keyup focusout", function () {
            validateSEOInput('HaberDTO_SEO');
        });

        $("#HaberDTO_SEOEN").on('keyup change', function () {
            validateSEOInput('HaberDTO_SEOEN');
        });

        $('#HaberDTO_SEOEN').bind("keyup focusout", function () {
            validateSEOInput('HaberDTO_SEOEN');
        });

        function validateSEOInput(id) {
            var charMap = { Ç: 'c', Ö: 'o', Ş: 's', İ: 'i', I: 'i', Ü: 'u', Ğ: 'g', ç: 'c', ö: 'o', ş: 's', ı: 'i', ü: 'u', ğ: 'g' };
            var str = $("#" + id).val();
            str_array = str.split('');
            for (var i = 0, len = str_array.length; i < len; i++) {
                str_array[i] = charMap[str_array[i]] || str_array[i];
            }
            str = str_array.join('');
            var clearStr = str.replace("&", "-").replace(",", "").replace(".", "").replace(" ", "-").replace("--", "-").replace("/", "").replace(/'/g, "").toLowerCase();
            $("#" + id).val(clearStr);
        }



        function gorselKaldır() {
            $("#Resim").attr('src', '/img/null.png');
            $('#Gorsel').val("");
        };

        function gorselKaldırEN() {
            $("#ResimEN").attr('src', '/img/null.png');
            $('#GorselEN').val("");
        };

        CKEDITOR.replace('HaberDTO.Detay');
        CKEDITOR.replace('HaberDTO.DetayEN');

        $(document).ready(function () {
            

            $("#Gorsel").change(function (e) {

                $("#Resim").removeAttr('src');
                $("#Resim").attr('src', URL.createObjectURL(e.target.files[0]));
            });
            $("#GorselEN").change(function (e) {

                $("#ResimEN").removeAttr('src');
                $("#ResimEN").attr('src', URL.createObjectURL(e.target.files[0]));
            });
        });

        $(document).ready(function () {
            habervalidator = $("#haberform").validate({
                rules: {
                    'HaberDTO.Isim': {
                        required: true,
                    },
                    'HaberDTO.SEO': {
                        required: true
                    },
                    'HaberDTO.IsimEN': {
                        required: true,
                    },
                    'HaberDTO.SEOEN': {
                        required: true
                    }
                },
                messages: {
                    'HaberDTO.Isim': {
                        required: "Bu alan boş geçilemez."
                    },
                    'HaberDTO.SEO': {
                        required: "Bu alan boş geçilemez."
                    },
                    'HaberDTO.IsimEN': {
                        required: "Bu alan boş geçilemez."
                    },
                    'HaberDTO.SEOEN': {
                        required: "Bu alan boş geçilemez."
                    }
                }
            });
        });

        
        var habervalidator;

        function haberEkle() {
            if (habervalidator.form()) {
                return true;
            }
            else {
                swal.fire({
                    text: "Lütfen bilgileri eksiksiz giriniz.",
                    icon: "error",
                    buttonsStyling: true,
                    confirmButtonText: "Tamam",
                    customClass: {
                        confirmButton: "btn font-weight-bold btn-light-primary"
                    }
                })


                return false;
            }
        }
    </script>

 }

Zemedya.AspNetCoreMVC/Views/Panel/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

Osen Kariyer

Zemedya.AspNetCoreMVC/Views/Panel/OdaGuncelle.cshtml
@{
    ViewData["Title"] = "OdaGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>OdaGuncelle</h1>

Zemedya.AspNetCoreMVC/Views/Panel/Odalar.cshtml
@model IEnumerable<Zemedya.Entity.Concrete.OdaEntities.Oda>
@{
    ViewData["Title"] = "Odalar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container ">
    <div class="card card-custom">
        <div class="card-header flex-wrap-border-0 pt-6 pb-0">

            <div class="card-title">
                <h3 class="card-label font-size-h3-lg mb-7">
                    <i class="flaticon2-gear text-primary"></i>
                    Oda Listesi
                </h3>
            </div>

            <div>
                <a asp-action="UrunEkle" asp-controller="Panel" class="btn btn-primary font-weight-bolder">
                    <i class="fas fa-plus"></i>	Yeni Ekle
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="example-preview">
                <table class="table table-striped table-hover table-bordered " id="dataTable" style="width:100%">
                    <thead>
                        <tr>
                            <th scope="col">Sıralama No</th>
                            <th scope="col">İsim</th>
                            @*@if (ViewBag.kategori == "True")
                            {
                                <th scope="col">Kategori</th>
                            }*@
                            <th scope="col" style="width:50px;">Aktif</th>
                            <th scope="col" style="width:50px;">Güncelle</th>
                            <th scope="col" style="width:50px;">Sil</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.SıraNo</td>
                                <td>@item.Isim</td>
                                @*@if (ViewBag.kategori == "True")
                                {
                                    <td>@item.UrunKategori.Isim</td>
                                }*@

                                <td>
                                    @if (item.Aktif)
                                    {
                                        <a data-id="@item.Id" class="aktif btn btn-sm font-weight-bold btn-light-primary btn-inline ml-2">Aktif</a>
                                    }
                                    else
                                    {
                                        <a data-id="@item.Id" class="aktif btn btn-sm font-weight-bold btn-light-danger btn-inline ml-2">Pasif</a>
                                    }

                                </td>
                                <td>
                                    <a href="/Panel/OdaGuncelle/@item.Id"><i class="flaticon-refresh text-warning icon-xl ml-8"></i></a>
                                </td>
                                <td>
                                    <a data-id="@item.Id" class="Sil btn flaticon-delete text-danger icon-xl ml-2"></a>
                                </td>

                            </tr>

                        }



                    </tbody>
                </table>
            </div>
        </div>
    </div>



</div>

@section Javascript{
    <script type="text/javascript">

        $(document).ready(function () {
            $(".Sil").on("click", function () {
                var Id = $(this).attr("data-id");
                var data = new FormData();
                data.append("Id", Id);
                Swal.fire({
                title: "Oda silinecek, Emin misiniz?",
                showCancelButton: true,
                confirmButtonText: "Evet",
                cancelButtonText: "İptal",
            }).then(function (result) {
                if (result.value) {

                    $.ajax({
                    url: '@Url.Action("OdaSil", "Panel")',
                    type: "POST",
                    processData: false,
                    contentType: false,
                    data: data,
                    success: function (data) {
                        swal.fire({
                            text: "Oda Başarıyla Silindi.",
                            icon: "success",
                            buttonsStyling: true,
                            confirmButtonText: "Tamam",
                            customClass: {
                                confirmButton: "btn font-weight-bold btn-light-primary"
                            }
                        }).then((result) => {
                            if (result.isConfirmed) {
                                window.location.reload();
                            }
                        })
                    }
                });
                }
            });
            });
        });

        $(document).ready(function () {
            $('#dataTable').DataTable();
        });

        $(document).ready(function () {
            $(".aktif").on("click", function () {
                var Id = $(this).attr("data-id");
                var data = new FormData();
                data.append("Id", Id);
                $.ajax({
                    url: '@Url.Action("PasifeCevirOda", "Panel")',
                    type: "POST",
                    processData: false,
                    contentType: false,
                    data: data,
                    success: function (data) {
                        window.location.reload();
                    }
                });
            });
        });


    </script>
}