Zemedya.AspNetCoreMVC/NavbarComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Zemedya.Business.Abstract.UnitOfWork;
using Zemedya.Model.VM.Page;

namespace Zemedya.AspNetCoreMVC.NavbarComponents
{
    public class FooterViewComponent : ViewComponent
    {
        private IUnitOfWork _unitOfWork;
        public FooterViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IViewComponentResult Invoke()
        {
            FooterVM footerVM = new FooterVM();
            footerVM.Iletisim = _unitOfWork.IletisimManager.Getir(x => x.Aktif);
            footerVM.Ayarlar = _unitOfWork.AyarlarManager.Getir(x => x.Id == 1);
            footerVM.Duyurular = _unitOfWork.DuyuruManager.HepsiniGetir(x => x.Aktif);
            return View(footerVM);
        }
    }
}

Zemedya.AspNetCoreMVC/NavbarComponents/NavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Zemedya.Business.Abstract.UnitOfWork;
using Zemedya.Model.VM.Page;

namespace Zemedya.AspNetCoreMVC.NavbarComponents
{
    public class NavbarViewComponent : ViewComponent
    {
        private IUnitOfWork _unitOfWork;
        public NavbarViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IViewComponentResult Invoke()
        {
            NavbarVM navbarVM = new NavbarVM
            {
                KurumsalListesi = _unitOfWork.KurumsalManager.HepsiniGetir(x => x.Aktif),
                BlogKategorileri = _unitOfWork.BlogKategoriManager.HepsiniGetir(x => x.Aktif),
                //UrunKategorileri = _unitOfWork.UrunKategoriManager.HepsiniGetir(x => x.Aktif),
                //AltKategoriler = _unitOfWork.UrunKategoriManager.HepsiniGetir(x => x.UstKategoriId != 1 || x.Aktif == true),
                MevcutSayfalar = _unitOfWork.MevcutSayfalarManager.Getir(x => x.Id == 1),
                MevcutDiller = _unitOfWork.MevcutDillerManager.Getir(x => x.Id == 1),
                EtkinlikListesi = _unitOfWork.EtkinlikManager.HepsiniGetir(x => x.Aktif),
                Ayarlar = _unitOfWork.AyarlarManager.Getir(x => x.Id == 1),
                DuyuruListesi = _unitOfWork.DuyuruManager.HepsiniGetir(x => x.Aktif)
            };
            return View(navbarVM);
        }
    }
}

Zemedya.AspNetCoreMVC/NavbarComponents/PanelNavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Zemedya.Business.Abstract.UnitOfWork;

namespace Zemedya.AspNetCoreMVC.NavbarComponents
{
    public class PanelNavbarViewComponent : ViewComponent
    {
        private IUnitOfWork _unitOfWork;
        public PanelNavbarViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IViewComponentResult Invoke()
        {
            var sayfa = _unitOfWork.MevcutSayfalarManager.Getir(x => x.Id == 1);
            return View(sayfa);
        }
    }
}

Zemedya.AspNetCoreMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Zemedya Panel</title>
    <meta name="description" content="Updates and statistics" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!--begin::Fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />        <!--end::Fonts-->
    <!--begin::Page Vendors Styles(used by this page)-->
    <link href="~/Panel/assets/plugins/custom/fullcalendar/fullcalendar.bundle.css?v=7.0.6" rel="stylesheet" type="text/css" />
    <!--end::Page Vendors Styles-->
    <!--begin::Global Theme Styles(used by all pages)-->
    @*<link href="~/Panel/assets/plugins/global/plugins.bundle.css?v=7.0.6" rel="stylesheet" type="text/css" />*@
    <link href="~/Panel/assets/plugins/custom/prismjs/prismjs.bundle.css?v=7.0.6" rel="stylesheet" type="text/css" />
    <link href="~/css/validation.css" rel="stylesheet" />
    <link href="~/Panel/assets/css/style.bundle2.css" rel="stylesheet" />
    <link href="~/Panel/assets/plugins/custom/datatables/datatables.bundle.css" rel="stylesheet" />
    <!--end::Global Theme Styles-->
    <!--begin::Layout Themes(used by all pages)-->
    <link href="~/Panel/assets/css/style.bundle.css?v=7.0.6" rel="stylesheet" type="text/css">
    <link href="~/Panel/assets/plugins/custom/prismjs/prismjs.bundle.css?v=7.0.6" rel="stylesheet" type="text/css">
    <link href="~/Panel/assets/plugins/global/plugins.bundle.css?v=7.0.6" rel="stylesheet" type="text/css">

</head>
<!--end::Head-->
<!--begin::Body-->
<body id="kt_body" class="header-fixed header-mobile-fixed page-loading">

    <!--begin::Main-->
    <!--begin::Header Mobile-->
    <div id="kt_header_mobile" class="header-mobile bg-primary  header-mobile-fixed ">
        <!--begin::Logo-->
        <a href="/Panel/Index">
            <img alt="Logo" src="~/img/zemedya-logo.png" class="max-h-30px" />
        </a>
        <!--end::Logo-->
        <!--begin::Toolbar-->
        <div class="d-flex align-items-center">

            <button class="btn p-0 burger-icon burger-icon-left ml-4" id="kt_header_mobile_toggle">
                <span></span>
            </button>

            <button class="btn p-0 ml-2" id="kt_header_mobile_topbar_toggle">
                <span class="svg-icon svg-icon-xl">
                    <!--begin::Svg Icon | path:assets/media/svg/icons/General/User.svg--><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <polygon points="0 0 24 0 24 24 0 24" />
                            <path d="M12,11 C9.790861,11 8,9.209139 8,7 C8,4.790861 9.790861,3 12,3 C14.209139,3 16,4.790861 16,7 C16,9.209139 14.209139,11 12,11 Z" fill="#000000" fill-rule="nonzero" opacity="0.3" />
                            <path d="M3.00065168,20.1992055 C3.38825852,15.4265159 7.26191235,13 11.9833413,13 C16.7712164,13 20.7048837,15.2931929 20.9979143,20.2 C21.0095879,20.3954741 20.9979143,21 20.2466999,21 C16.541124,21 11.0347247,21 3.72750223,21 C3.47671215,21 2.97953825,20.45918 3.00065168,20.1992055 Z" fill="#000000" fill-rule="nonzero" />
                        </g>
                    </svg><!--end::Svg Icon-->
                </span>
            </button>
        </div>
        <!--end::Toolbar-->
    </div>
    <!--end::Header Mobile-->
    <div class="d-flex flex-column flex-root">
        <!--begin::Page-->
        <div class="d-flex flex-row flex-column-fluid page">
            <!--begin::Wrapper-->
            <div class="d-flex flex-column flex-row-fluid wrapper" id="kt_wrapper">
                <!--begin::Header-->
                <div id="kt_header" class="header flex-column  header-fixed ">
                    <!--begin::Top-->
                    <div class="header-top">
                        <!--begin::Container-->

                        <div class=" container ">
                            <div class="topbar">

                                @await Component.InvokeAsync("PanelNavbar")
                            </div>


                            <!--end::Topbar-->
                        </div>
                        <!--end::Container-->
                    </div>
                    <!--end::Top-->
                </div>
                <!--end::Header-->
                <!--begin::Content-->
                <div class="content  d-flex flex-column flex-column-fluid" id="kt_content">
                    @RenderBody()
                </div>
                <!--end::Content-->
                <!--begin::Footer-->
                <!--end::Footer-->
            </div>
            <!--end::Wrapper-->
        </div>
        <!--end::Page-->
    </div>

    <!--begin::Global Config(global config for global JS scripts)-->
    <script>
        var KTAppSettings = {
            "breakpoints": {
                "sm": 576,
                "md": 768,
                "lg": 992,
                "xl": 1200,
                "xxl": 1200
            },
            "colors": {
                "theme": {
                    "base": {
                        "white": "#ffffff",
                        "primary": "#0BB783",
                        "secondary": "#E5EAEE",
                        "success": "#1BC5BD",
                        "info": "#8950FC",
                        "warning": "#FFA800",
                        "danger": "#F64E60",
                        "light": "#F3F6F9",
                        "dark": "#212121"
                    },
                    "light": {
                        "white": "#ffffff",
                        "primary": "#D7F9EF",
                        "secondary": "#ECF0F3",
                        "success": "#C9F7F5",
                        "info": "#EEE5FF",
                        "warning": "#FFF4DE",
                        "danger": "#FFE2E5",
                        "light": "#F3F6F9",
                        "dark": "#D6D6E0"
                    },
                    "inverse": {
                        "white": "#ffffff",
                        "primary": "#ffffff",
                        "secondary": "#212121",
                        "success": "#ffffff",
                        "info": "#ffffff",
                        "warning": "#ffffff",
                        "danger": "#ffffff",
                        "light": "#464E5F",
                        "dark": "#ffffff"
                    }
                },
                "gray": {
                    "gray-100": "#F3F6F9",
                    "gray-200": "#ECF0F3",
                    "gray-300": "#E5EAEE",
                    "gray-400": "#D6D6E0",
                    "gray-500": "#B5B5C3",
                    "gray-600": "#80808F",
                    "gray-700": "#464E5F",
                    "gray-800": "#1B283F",
                    "gray-900": "#212121"
                }
            },
            "font-family": "Poppins"
        };
    </script>
    <!--end::Global Config-->
    <!--begin::Global Theme Bundle(used by all pages)-->
    @*<script src="~/Panel/assets/plugins/global/plugins.bundle.js?v=7.0.6"></script>
        <script src="~/Panel/assets/plugins/custom/prismjs/prismjs.bundle.js?v=7.0.6"></script>
        <script src="~/Panel/assets/js/scripts.bundle.js?v=7.0.6"></script>*@

    <!--end::Global Theme Bundle-->
    <!--begin::Page Vendors(used by this page)-->
    <script src="~/Panel/assets/plugins/custom/fullcalendar/fullcalendar.bundle.js?v=7.0.6"></script>
    <!--end::Page Vendors-->
    <!--begin::Page Scripts(used by this page)-->
    <script src="~/Panel/assets/js/pages/widgets.js?v=7.0.6"></script>
    <script src="~/js/jquery.min.js"></script>
    @*<script src="~/Panel/assets/js/scripts.bundle.js"></script>*@


    <script src="~/Panel/assets/plugins/global/plugins.bundle.js?v=7.0.6"></script>
    <script src="~/Panel/assets/plugins/custom/prismjs/prismjs.bundle.js?v=7.0.6"></script>
    <script src="~/Panel/assets/js/scripts.bundle.js?v=7.0.6"></script>

    <script src="~/Panel/assets/js/pages/crud/datatables/basic/headers.js"></script>
    <script src="~/Panel/assets/plugins/custom/datatables/datatables.bundle.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="~/js/jquery.validate.js"></script>

    @RenderSection("Javascript", false)
    <!--end::Page Scripts-->
</body>
<!--end::Body-->
</html>

Zemedya.AspNetCoreMVC/Views/Shared/_PageLayout.cshtml
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">
    <meta @ViewData["googledogrulama"]>
    <title id="Title">@ViewData["Title"]</title>
    <link rel="shortcut icon" id="icon" href="~/img/@ViewData["favicon"]" type="image/x-icon">
    <meta name="description" content="@ViewData["description"]">

    <link rel="stylesheet" href="/osen/assets/css/vendor.css" />
    <link rel="stylesheet" href="/osen/assets/css/style.css" />

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Sora:wght@300;400;500;700&display=swap" rel="stylesheet">


    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', '@ViewData["googleanalytics"]', 'auto');
        ga('send', 'pageview');

    </script>


</head>

<body>

    @await Component.InvokeAsync("Navbar")
    @RenderBody()



    <!-- Page Footer  -->
    @await Component.InvokeAsync("Footer")



    <script src="/osen/assets/js/vendor.min.js"></script>
    <script src="/osen/assets/js/app.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

    <script src="~/js/jquery.validate.js"></script>
    @*<script src="~/Page/js\main.js"></script>*@
    @RenderSection("Javascript", false)

    <script type="text/javascript">
        $(".LanguageTR").on("click", function () {


            localStorage.removeItem("lang");
            localStorage.setItem("lang", "tr");
        });

        $(".LanguageEN").on("click", function () {

            localStorage.removeItem("lang");
            localStorage.setItem("lang", "en");
        });



        var lang = localStorage.getItem("lang");
        if (lang == "en") {

            document.getElementById("navbarTR").remove();
        }
        else {

            document.getElementById("navbarEN").remove();
        };
    </script>
</body>

</html>