Zemedya.AspNetCoreMVC/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Zemedya.Business.Abstract.UnitOfWork;
using Zemedya.Entity.Concrete.BlogEntities;
using Zemedya.Entity.Concrete.DuyuruEntities;
using Zemedya.Entity.Concrete.EtkinlikEntities;
using Zemedya.Entity.Concrete.KariyerFirsatlariEntities;
using Zemedya.Entity.Concrete.VideoEntities;
using Zemedya.Model.DTO.EmailDTOs;
using Zemedya.Model.VM.Page;

namespace Zemedya.AspNetCoreMVC.Controllers
{
    public class PageController : Controller
    {
        private IUnitOfWork _unitOfWork;
        public PageController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        [Route("")]
        public IActionResult Media()
        {
            var siteBilgisi = _unitOfWork.AyarlarManager.Getir(x => x.Id == 1);
            if (siteBilgisi.GoogleDogrulamaKodu != null)
            {
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Trim();
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Replace('"', ' ');
                int koduzunluk = siteBilgisi.GoogleDogrulamaKodu.Length - 6;
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Substring(5, koduzunluk);
            }
            List<Etkinlik> etkinlikler = new List<Etkinlik>();
            List<KariyerFirsati> kariyerFirsatlari = new List<KariyerFirsati>();
            List<Duyuru> duyurular = new List<Duyuru>();
            for (int i = 0; i < 4; i++)
            {
                Etkinlik etkinlik = _unitOfWork.EtkinlikManager.HepsiniGetir(x => x.Aktif).ElementAtOrDefault(i);
                etkinlikler.Add(etkinlik);
                
            }
            for (int i = 0; i < 10; i++)
            {
                KariyerFirsati kariyerFirsati = _unitOfWork.KariyerFirsatiManager.HepsiniGetir(x => x.Aktif).ElementAtOrDefault(i);
                kariyerFirsatlari.Add(kariyerFirsati);

            }
            for (int i = 0; i < 3; i++)
            {
                Duyuru duyuru = _unitOfWork.DuyuruManager.HepsiniGetir(x => x.Aktif).ElementAtOrDefault(i);
                duyurular.Add(duyuru);

            }
            if (siteBilgisi.SiteTitle == null)
            {
                siteBilgisi.SiteTitle = "Zemedya";
            }
            if (siteBilgisi.GoogleAnalyticsKodu == null)
            {
                siteBilgisi.GoogleAnalyticsKodu = "google";
            }
            AnasayfaVM anasayfaVM = new AnasayfaVM()
            {
                Title = siteBilgisi.SiteTitle.Trim(),
                GoogleDogrulama = siteBilgisi.GoogleDogrulamaKodu,
                Favicon = siteBilgisi.Favicon,
                GoogleAnalytics = siteBilgisi.GoogleAnalyticsKodu.Trim(),
                KariyerFirsatiListesi = kariyerFirsatlari,
                EtkinlikListesi = etkinlikler,
                Kurumsal = _unitOfWork.KurumsalManager.Getir(x => x.Aktif == true),
                DuyuruListesi = duyurular
            };
            if (siteBilgisi.Description != null)
            {
                ViewBag.description = siteBilgisi.Description.Trim();
            }
            
            return View(anasayfaVM);
        }

        [Route("/en")]
        public IActionResult MediaEN()
        {
            var siteBilgisi = _unitOfWork.AyarlarManager.Getir(x => x.Id == 1);
            if (siteBilgisi.GoogleDogrulamaKodu != null)
            {
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Trim();
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Replace('"', ' ');
                int koduzunluk = siteBilgisi.GoogleDogrulamaKodu.Length - 6;
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Substring(5, koduzunluk);
            }
            List<Etkinlik> etkinlikler = new List<Etkinlik>();
            List<KariyerFirsati> kariyerFirsatlari = new List<KariyerFirsati>();
            List<Duyuru> duyurular = new List<Duyuru>();
            for (int i = 0; i < 4; i++)
            {
                Etkinlik etkinlik = _unitOfWork.EtkinlikManager.HepsiniGetir(x => x.Aktif).ElementAtOrDefault(i);
                etkinlikler.Add(etkinlik);

            }
            for (int i = 0; i < 10; i++)
            {
                KariyerFirsati kariyerFirsati = _unitOfWork.KariyerFirsatiManager.HepsiniGetir(x => x.Aktif).ElementAtOrDefault(i);
                kariyerFirsatlari.Add(kariyerFirsati);

            }
            for (int i = 0; i < 3; i++)
            {
                Duyuru duyuru = _unitOfWork.DuyuruManager.HepsiniGetir(x => x.Aktif).ElementAtOrDefault(i);
                duyurular.Add(duyuru);

            }
            if (siteBilgisi.SiteTitleEN == null)
            {
                siteBilgisi.SiteTitleEN = "Zemedya";
            }
            if (siteBilgisi.GoogleAnalyticsKodu == null)
            {
                siteBilgisi.GoogleAnalyticsKodu = "google";
            }
            AnasayfaVM anasayfaVM = new AnasayfaVM()
            {
                Title = siteBilgisi.SiteTitleEN.Trim(),
                GoogleDogrulama = siteBilgisi.GoogleDogrulamaKodu,
                Favicon = siteBilgisi.Favicon,
                GoogleAnalytics = siteBilgisi.GoogleAnalyticsKodu.Trim(),
                KariyerFirsatiListesi = kariyerFirsatlari,
                EtkinlikListesi = etkinlikler,
                Kurumsal = _unitOfWork.KurumsalManager.Getir(x => x.Aktif == true),
                DuyuruListesi = duyurular
            };
            if (siteBilgisi.DescriptionEN != null)
            {
                ViewBag.description = siteBilgisi.DescriptionEN.Trim();
            }
            return View(anasayfaVM);
        }


        [Route("iletisim")]
        public IActionResult Iletisim()
        {
            var siteBilgisi = _unitOfWork.AyarlarManager.Getir(x => x.Id == 1);
            if (siteBilgisi.GoogleDogrulamaKodu != null)
            {
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Trim();
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Replace('"', ' ');
                int koduzunluk = siteBilgisi.GoogleDogrulamaKodu.Length - 6;
                siteBilgisi.GoogleDogrulamaKodu = siteBilgisi.GoogleDogrulamaKodu.Substring(5, koduzunluk);
            }
            var iletisim = _unitOfWork.IletisimManager.Getir(x => x.Id == 1);
            ViewBag.googledogrulama = siteBilgisi.GoogleDogrulamaKodu;
            if (siteBilgisi.Description != null)
            {
                ViewBag.description = siteBilgisi.Description.Trim();
            }
            if (siteBilgisi.GoogleAnalyticsKodu != null)
            {
                ViewBag.googleanalytics = siteBilgisi.GoogleAnalyticsKodu.Trim();
            }
            ViewBag.favicon = siteBilgisi.Favicon;
            iletisim.Ayarlar = siteBilgisi;
            return View(iletisim);
        }





        public ActionResult EmailGonder([FromForm] EmailDTO emailDTO, IFormFile dosya)
        {
            try
            {
                var ayarlar = _unitOfWork.AyarlarManager.Getir(x => x.Id == 1);
                SmtpClient client = new SmtpClient(ayarlar.Server, int.Parse(ayarlar.Port));
                client.Credentials = new NetworkCredential(ayarlar.Adres, ayarlar.Sifre);
                client.EnableSsl = false;
                MailMessage msj = new MailMessage();
                
                    msj.From = new MailAddress(emailDTO.EpostaAdı, emailDTO.Ad + " " + emailDTO.Soyad + " "+ emailDTO.EpostaAdı);
                    msj.To.Add(ayarlar.IletilecekAdres);


                

                    msj.Subject = emailDTO.Konu;
                
                
                msj.Body =  "Mesaj : " +  emailDTO.Mesaj + Environment.NewLine +  "Telefon : " + emailDTO.Telefon + Environment.NewLine + "Ad : " + emailDTO.Ad + Environment.NewLine + "Soyad : " + emailDTO.Soyad + Environment.NewLine + "Email : " + emailDTO.EpostaAdı ;
                if (emailDTO.kurumsal != null)
                {
                    msj.Body = msj.Body + Environment.NewLine + "İletişim Tipi : " + emailDTO.kurumsal;
                }
                if (emailDTO.kurumAdi != null || emailDTO.kurumsalpozisyon != null)
                {
                    msj.Body = msj.Body + Environment.NewLine + "Kurum Adı : " + emailDTO.kurumAdi ?? "" + Environment.NewLine + "Kurumsal Pozisyon : " + emailDTO.kurumsalpozisyon  ?? "";
                }
                if (dosya != null)
                {
                    string FileName = Path.GetFileName(dosya.FileName);
                    msj.Attachments.Add(new Attachment(dosya.OpenReadStream(), FileName));
                }
                client.Send(msj);
                return Json(new
                {
                    success = true,
                    result = 1
                });

            }
            catch (Exception e)
            {

                return Json(new
                {
                    success = true,
                    result = 2
                });
            }
            
        }

      





        public ActionResult SiteBilgileri(string bilgi)
        {
            var ayarlar = _unitOfWork.AyarlarManager.Getir(x => x.Id == 1);
            return Json(new
            {
                success = true,
                whatsapptel = ayarlar.WhatsappTelefon,
                whatsappdurum = ayarlar.WhatsappDurum,
                whatsappMesaj = ayarlar.WhatsappMesaj,
                canlidestek = ayarlar.CanliDestekKodu,
                canlidestekaktif = ayarlar.CanliDestekAktif
            });
        }

        [Route("hizmetlerimiz/{seo}")]
        [Route("our-services/{seo}")]

Zemedya.AspNetCoreMVC/Views/Page/Basvuru.cshtml
@model IEnumerable<Zemedya.Entity.Concrete.KariyerFirsatlariEntities.KariyerFirsati>
@{
    ViewData["Title"] = "KariyerBasvuru";
    ViewData["description"] = ViewBag.description;
    ViewData["googledogrulama"] = ViewBag.googleDogrulama;
    ViewData["favicon"] = ViewBag.favicon;
    ViewData["googleanalytics"] = ViewBag.googleanalytics;
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<section class="hero pb-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-12 text-white d-none d-lg-block" style="background-image: url(/osen/assets/images/gorsel.jpeg); padding: 90px; background-position-y: -100px; background-position-x: -100px;">

                <h1 class="mb-2 text-shadow">Kariyer Başvuru</h1>

            </div>
            <div class="col-md-12 col-lg-12 text-white d-block d-sm-none" style="background-image: url(/osen/assets/images/gorsel-mobil-alt-sayfa.jpeg); padding: 60px;">

                <h1 class="mb-2 text-shadow">Kariyer Başvuru</h1>

            </div>
        </div>
    </div>
</section>

<section>
    <form id="Emailform" method="post">
        <div class="container">
            <div class="row">

                <div class="col-lg-8">
                    <div class="row gutter-2">
                        <div class="form-group col-md-6">
                            <label>AD *</label>
                            <input type="text" class="form-control" id="name" name="name">
                        </div>
                        <div class="form-group col-md-6">
                            <label>SOYAD *</label>
                            <input type="text" class="form-control" id="surname" name="surname">
                        </div>
                        <div class="form-group col-md-6">
                            <label>TELEFON *</label>
                            <input type="tel" class="form-control" id="phone" name="phone">
                        </div>
                        <div class="form-group col-md-6">
                            <label>EMAİL *</label>
                            <input type="email" class="form-control" id="email" name="email">
                        </div>
                        <div class="form-group col-12">
                            <label for="inputNameSecond">KONU</label>
                            <input type="text" class="form-control" id="subject" name="subject" value="@Model.LastOrDefault().Pozisyon">
                        </div>
                        <div class="form-group col-12">
                            <label for="inputTextarea">MESAJ</label>
                            <textarea class="form-control" rows="4" id="message" name="message"></textarea>
                        </div>
                        <div class="col-12 pb-0">
                            <label class="mb-0">CV *</label>
                        </div>
                        <div class="col-12"> <input type="file" class="" id="file" name="file"> </div>
                        <div class="col-12">
                            <p class="small">* işaretli alanların doldurulası zorunludur.</p>
                        </div>
                        <div class="col-12">
                            <p class="small">Yükleyebileceğiniz dosya en fazla 2 MB boyutunda ve <strong> PDF</strong>, <strong> DOC</strong> veya <strong> DOCX</strong> formatlarında olabilir.</p>
                        </div>
                        <div class="col-12">
                            <input type="checkbox" class="" id="contract" name="contract">
                            <label for="contract" style="padding-left: 23px;margin-top: -16px;">
                                <strong class="black-text">Kişisel Veri Kaydı Onay Formu *</strong>
                                <p>İş bulma ve yerleştirme kapsamında, kendi yararım için tarafıma danışmanlık hizmeti sunan Osen Kariyer'in, işbu danışmanlık hizmeti dahilinde sosyal medya veya iş bulma konusunda hizmet veren her türlü mecrada ve internet mecrasında bulunan özgeçmişimi kullanmaya, işbu özgeçmişin içinde bulunan kişisel verilerimin ve varsa hassas kişisel verilerimin sadece iş bulma ve yerleştirme kapsamındaki danışmanlık hizmeti amacıyla Türkiye ve/veya yurt dışında kaydedilmesine, kullanılmasına, aktarılmasına ve işlenmesine 6698 sayılı Kişisel Verilerin Korunması Kanunu’na uygun olarak açıkça muvafakat ederim. </p>

                                <p>
                                    Ayrıca Osen Kariyer tarafından kaydedilmesine, kullanılmasına, aktarılmasına ve işlenmesine dair verdiğim açık muvafakate rağmen,  Osen Kariyer'in veri tabanına kaydedilmiş ve işlenmiş kişisel verilerimin ve varsa hassas kişisel verilerimin en fazla 10 yıl süreyle saklanacağını, ancak talebim üzerine kişisel verilerimin ve varsa hassas kişisel verilerimin anonimleştirileceği veya tamamen veri tabanından silineceği konusunda açıkça bilgilendirildim.


                                </p>
                            </label>
                        </div>
                        <div class="col-12">
                            <button onclick="return epostaGonder()" class="btn btn-primary mt-2">GÖNDER</button>
                        </div>
                    </div>
                </div>


                <div class="col-lg-4">
                    <aside>
                        <h5 class="text-primary" style="text-align: center;font-weight:700;">KARİYER FIRSATLARI</h5>
                        @*<div class="jobs">
                            @foreach (var item in Model)
                            {
                                if (item != Model.LastOrDefault())
                                {
                                    if (item != null)
                                    {
                                        <div class="item">
                                            <a href="/kariyer-firsatlari/@item.SEO">
                                                <p class="title">@item.Pozisyon (@item.Sehir)</p>
                                                <p class="">@item.IsAlani - @item.Sehir</p>
                                                <p class="date">@item.Tarih.Day-@item.Tarih.Month-@item.Tarih.Year</p>
                                            </a>
                                        </div>
                                    }
                                }

                            }

                        </div>*@

                        <ul class="list-group">
                            <li class="list-group-item" style="text-align: center; background-color: #103948;">
                                <a href="/kariyer-firsatlari" class="eyebrow action">Tümünü Gör</a>
                            </li>
                        </ul>
                    </aside>
                </div>
            </div>

        </div>
    </form>

</section>

@section Javascript{
    <script type="text/javascript">
        $(document).ready(function () {
            habervalidator = $("#Emailform").validate({
                rules: {
                    name: {
                        required: true,
                    },
                    contract: {
                        required: true,
                    },
                    surname: {
                        required: true,
                    },
                    email: {
                        required: true,
                        email: true,
                    },
                    phone: {
                        required: true,
                    },
                    subject: {
                        required: true,
                    },
                    message: {
                        required: true,
                    }
                },
                messages: {
                    name: {
                        required: "Bu alan boş geçilemez."
                    },
                    contract: {
                        required: "Bu alan boş geçilemez."
                    },
                    surname: {
                        required: "Bu alan boş geçilemez."
                    },
                    phone: {
                        required: "Bu alan boş geçilemez."
                    },
                    email: {
                        required: "Bu alan boş geçilemez.",
                        email : "Lütfen geçerli bir e-posta adresi giriniz."
                    },
                    subject: {
                        required: "Bu alan boş geçilemez."
                    },
                    message: {
                        required: "Bu alan boş geçilemez."
                    }
                }
            });
        });

        function EpostaGonder() {
            var file = $("#file").get(0).files;
            var form = new FormData();
            form.append("EpostaAdı", $('#email').val());
            form.append("Ad", $('#name').val());
            form.append("Soyad", $('#surname').val());
            form.append("Konu", $('#subject').val());
            form.append("Mesaj", $('#message').val());
            form.append("Telefon", $('#phone').val());
            form.append("dosya", file[0]);

            $.ajax({
                url: '@Url.Action("EmailGonder", "Page")',
                type: "POST",
                processData: false,
                contentType: false,
                data: form,
                success: function (data) {
                    if (data.result == 1) {
                        swal.fire({
                            text: "Mesajınız başarıyla gönderildi.",
                            icon: "success",
                            buttonsStyling: true,
                            confirmButtonText: "Tamam",
                            customClass: {
                                confirmButton: "btn font-weight-bold btn-light-primary"
                            }
                        })
                    }
                    else {
                        swal.fire({
                            text: "Mesaj Gönderilemedi.",
                            icon: "error",
                            buttonsStyling: true,
                            confirmButtonText: "Tamam",
                            customClass: {
                                confirmButton: "btn font-weight-bold btn-light-primary"
                            }
                        })
                    }
                }
            });
        }

        var habervalidator;

        function epostaGonder() {
            if (habervalidator.form()) {
                EpostaGonder();
                return false;
            }
            else {
                swal.fire({
                    text: "Lütfen bilgileri eksiksiz giriniz.",
                    icon: "error",
                    buttonsStyling: true,
                    confirmButtonText: "Tamam",
                    customClass: {
                        confirmButton: "btn font-weight-bold btn-light-primary"
                    }
                })


                return false;
            }
        }
    </script>
}

Zemedya.AspNetCoreMVC/Views/Page/Blog.cshtml
@model IEnumerable<Zemedya.Entity.Concrete.EtkinlikEntities.Etkinlik>
@{
    ViewData["Title"] = "Blog";
    ViewData["description"] = ViewBag.description;

    ViewData["googledogrulama"] = ViewBag.googleDogrulama;
    ViewData["favicon"] = ViewBag.favicon;
    ViewData["googleanalytics"] = ViewBag.googleanalytics;
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<section class="hero pb-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-12 text-white d-none d-lg-block" style="background-image: url(/osen/assets/images/gorsel.jpeg); padding: 90px; background-position-y: -100px; background-position-x: -100px;">

                <h1 class="mb-2 text-shadow">Blog</h1>

            </div>
            <div class="col-md-12 col-lg-12 text-white d-block d-sm-none" style="background-image: url(/osen/assets/images/gorsel-mobil-alt-sayfa.jpeg); padding: 60px;">

                <h1 class="mb-2 text-shadow">Blog</h1>

            </div>
        </div>
    </div>
</section>

<section class="pt-5">
    <div class="container">



        <div class="row">
            @foreach (var item in Model)
            {

                <div class="col-md-3">
                    <div class="blog-card" style="margin-bottom: 25px;">
                        <div class="blog-card_img">
                            <a href="/blog/@item.SEO" class="card card-equal equal-50 equal-md-100 card-scale vitrin-gorsel" style="border-radius: 10px;">
                                <span class="image image-overlay" style="background-image: url(/img/@item.Gorsel)"></span>
                            </a>
                        </div>
                        <div class="blog-card_body py-2">
                            <h5><a style=" color: black;" href="/blog/@item.SEO">@item.Isim</a></h5>
                            <p style="font-size: 0.9rem;">@item.Ozet</p>
                        </div>
                        <div class="blog-card_footer"><a href="/blog/@item.SEO">Devamını Oku →</a></div>
                    </div>
                </div>
            }
           

        </div>
    </div>


</section>

Zemedya.AspNetCoreMVC/Views/Page/BlogDetay.cshtml
@model Zemedya.Model.DTO.EtkinlikDTOs.EtkinlikDTO
@{
    @if (ViewBag.en == "True")
    {
        ViewData["Title"] = Model.IsimEN;
        ViewData["description"] = ViewBag.descriptionEN;
    }
    else
    {
        ViewData["Title"] = Model.Isim;
        ViewData["description"] = ViewBag.description;
    }



    ViewData["googledogrulama"] = ViewBag.googleDogrulama;
    ViewData["favicon"] = ViewBag.favicon;
    ViewData["googleanalytics"] = ViewBag.googleanalytics;
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

@if (ViewBag.en == "True")
{
<section class="hero pb-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-12 text-white d-none d-lg-block" style="background-image: url(/osen/assets/images/gorsel.jpeg); padding: 90px; background-position-y: -100px; background-position-x: -100px;">

                <h1 class="mb-2 text-shadow">Blog</h1>

            </div>
            <div class="col-md-12 col-lg-12 text-white d-block d-sm-none" style="background-image: url(/osen/assets/images/gorsel-mobil-alt-sayfa.jpeg); padding: 60px;">

                <h1 class="mb-2 text-shadow">Blog</h1>

            </div>
        </div>
    </div>
</section>

    <section>
        <div class="container">
            <div class="row gutter-4 justify-content-between">
                <div class="col-lg-12">
                   


                    
                    @Html.Raw(Model.DetayEN)







                </div>
            </div>
        </div>
    </section>
}
else
{
<section class="hero pb-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-12 text-white d-none d-lg-block" style="background-image: url(/osen/assets/images/gorsel.jpeg); padding: 90px; background-position-y: -100px; background-position-x: -100px;">

                <h1 class="mb-2 text-shadow">Blog</h1>

            </div>
            <div class="col-md-12 col-lg-12 text-white d-block d-sm-none" style="background-image: url(/osen/assets/images/gorsel-mobil-alt-sayfa.jpeg); padding: 60px;">

                <h1 class="mb-2 text-shadow">Blog</h1>

            </div>
        </div>
    </div>
</section>

    <section>
        <div class="container">
            <div class="row gutter-4 justify-content-between">
                <div class="col-lg-12">
                   


                   
                    @Html.Raw(Model.Detay)







                </div>
            </div>
        </div>
    </section>
}

Zemedya.AspNetCoreMVC/Views/Page/Etkinlik.cshtml
@model Zemedya.Model.DTO.DuyuruDTOs.DuyuruDTO
@{
    @if (ViewBag.en == "True")
    {
        ViewData["Title"] = Model.IsimEN;
        ViewData["description"] = ViewBag.descriptionEN;
    }
    else
    {
        ViewData["Title"] = Model.Isim;
        ViewData["description"] = ViewBag.description;
    }



    ViewData["googledogrulama"] = ViewBag.googleDogrulama;
    ViewData["favicon"] = ViewBag.favicon;
    ViewData["googleanalytics"] = ViewBag.googleanalytics;
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}
@if (ViewBag.en == "True")
{
<section class="hero pb-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-12 text-white d-none d-lg-block" style="background-image: url(/osen/assets/images/gorsel.jpeg); padding: 90px; background-position-y: -100px; background-position-x: -100px;">

                <h1 class="mb-2 text-shadow">@Model.IsimEN</h1>

            </div>
            <div class="col-md-12 col-lg-12 text-white d-block d-sm-none" style="background-image: url(/osen/assets/images/gorsel-mobil-alt-sayfa.jpeg); padding: 60px;">

                <h1 class="mb-2 text-shadow">@Model.IsimEN</h1>

            </div>
        </div>
    </div>
</section>

    <section>
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12 mr-auto">
                    @Html.Raw(Model.DetayEN)

                    @*<p><br /><br /><a href="mailto:info@osenkariyer.com" class="eyebrow underline action">@Model.IsimEN için bize ulaşın</a> </p>*@



                </div>

            </div>

        </div>
    </section>
}
else
{
<section class="hero pb-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-12 text-white d-none d-lg-block" style="background-image: url(/osen/assets/images/gorsel.jpeg); padding: 90px; background-position-y: -100px; background-position-x: -100px;">

                <h1 class="mb-2 text-shadow">@Model.Isim</h1>

            </div>
            <div class="col-md-12 col-lg-12 text-white d-block d-sm-none" style="background-image: url(/osen/assets/images/gorsel-mobil-alt-sayfa.jpeg); padding: 60px;">

                <h1 class="mb-2 text-shadow">@Model.Isim</h1>

            </div>
        </div>
    </div>
</section>

    <section>
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12 mr-auto">
                    @Html.Raw(Model.Detay)

                    @*<p><br /><br /><a href="mailto:info@osenkariyer.com" class="eyebrow underline action">@Model.Isim için bize ulaşın</a> </p>*@



                </div>

            </div>

        </div>
    </section>
}